### ISSUE TITLE
엔터프라이즈 에서 한글화 지원

### ISSUE THREAD

**Issue by ossoni** [hatemogi/github-ko-ext#14]
깃헙 엔터프라이즈에서 사용하고싶은데 가능할지요?

**Comment by hatemogi** [comment]
가능합니다. 다만 익스텐션 사용 권한 부분에서, 귀사의 깃헙 주소를 등록해야 하는 문제가 있어요. 

세가지 해결 방법이 떠오르는데요,

## 1. 

우선, 공개 깃헙 주소 외에, 모든 사이트에대해서 권한 요청을 한다. 이렇게 되면, 공개 깃헙이나, 엔터프라이즈나 무관하게 다 쓸 수 있기는 한데요, 일반적 사용자 입장에서, 내가 쓰고자 하는 github.com외의 사이트에 대한 권한을 요청하니 거부감이 있을 수 있고, 크롬 웹스토어에 심사시에 왜 전체 사이트 권한을 요구하는지에 대해 해명을 해야하는 번거로움이 있습니다. 

## 2. 

다음은, 깃헙 엔터프라이즈 주소를 취합해서, (국내에서 깃헙 엔터프라이즈를 구매해서 사용할 수 있는 자금력의 회사는 그다지 많지 않을 테니..) 이 익스텐션에 넣어서 배포하는 방법인데, 각 회사 보안팀에서 이를 좋아할 것 같지 않습니다. 각사의 깃헙 엔터프라이즈는 이미 보안네트워크에 잘 들어있을 테지만, url이 노출되는 것만으로도 싫어하는 분들이 있을 것 같습니다. 저도 당시 다니던 회사의 깃헙 엔터프라이즈 주소를 넣을까 하다가, 망설여져서 공개 크롬익스텐션 버전에는 넣지 않았습니다.


## 3. 

세번째는, 각자 자기 회사의 깃헙 엔터프라이즈 주소를 넣어서 패치한 버전을, 회사 사내에서만 접근 가능한 회사 커뮤니티나 슬랙 채널등에 배포하는 겁니다. 크롬 웹스토어를 거치는 것이 아니긴 하지만, 소정의 목적을 달성할 수 있습니다.

예를들어, 깃헙 엔터프라이즈의 url이,

https://git.greatecompany.com

이라고 할 때,

https://github.com/hatemogi/github-ko-ext/blob/21c91222294f65d472c2ee30f923b163397e4bfd/chrome/manifest.json#L19

에, matches 부분에 해당 패턴을 추가해주시고 zip파일로 사내게시판에 배포를 하시면 됩니다.
사내 배포할 경우에는, permissions부분은 *로 모든 사이트에 대한 권한을 요청하면 됩니다.

이 두 부분을 수정하고, 빌드(make)하면, .zip파일이 생깁니다. 이 zip파일을 크롬 확장 프로그램으로 등록하게끔 유도하실 수 있어요.

이렇게 되면, 배포자도 직원이고, 배포 공간도 사내이고, 그걸 받을 수 있는 것도 사내이니, 보안팀이 문제시할 소지가 꽤 줄어들지 않을까 합니다. 


저는, 세번째 방법을 추천드리고 싶습니다.
