### ISSUE TITLE
README.md 도 같이 번역되면 좋을 것 같습니다. 

### ISSUE THREAD

**Issue by easylogic** [hatemogi/github-ko-ext#4]
좋은 툴 만들어주셔서 감사합니다.

**Comment by hatemogi** [comment]
좋은 의견 감사드립니다. README에 표시되는 프로젝트 설명을, 별도 번역 API를 호출해서 처리하는 방법이 있으면 적용할 수 있을 것 같습니다. 다만, 현재 백엔드를 거치지 않고 처리하고 있어서, 어떤 방법이 있을지 고심해봐야 할 듯 합니다.
