### ISSUE TITLE
firefox에서 이확장을 쓰면 왜 안되요?

### ISSUE THREAD

**Issue by gcqmkm02** [hatemogi/github-ko-ext#7]
안녕하세요.
firefox에서 github-ko-ext를 쓰고싶어요. 
firefox확장 만들면 어때요?
어디에서 시작 해야 되요?

**Comment by hatemogi** [comment]
아, 네 안녕하세요. 좋은 의견 감사드립니다. 아직 제가 firefox에서의 확장프로그램 구조를 살펴보지는 않았습니다만, chrome의 확장 프로그램과 크게 다르지 않을 것으로 예상합니다. firefox에서의 확장프로그램 구성을 하고, 핵심 .js파일은 거의 그대로 활용할 수 있을 것이라고 생각해요.

다만, 이 확장 프로그램이 GitHub 한국어 이용자에게, 쓸모가 있는지 아직 잘 모르겠어서, firefox는 물론, chrome에서의 추가 개발도 불확실한 상황입니다.
