### ISSUE TITLE
이 프로젝트 종료되었나요?

### ISSUE THREAD

**Issue by Moondream15** [hatemogi/github-ko-ext#8]
안녕하세요 github를 이용하면서 한국어로 번역되면 좋겠다 생각했는데 찾아보니까 이런 확장 프로그램을 알게 되었습니다
그런데 일부 번역 안되는 부분도 있는데 최근 업데이트가 없네요
이 프로젝트가 혹시 종료되었는지 궁금합니다.

**Comment by hsh2001** [comment]
프로젝트 종료 조건에 깃헙이 정식으로 한글화를 지원하면 종료한다고 적혀있는데, 최근에 깃헙이 점차 한글화를 지원하고 있습니다. 아마 자연스레 종료될 것 같네요!

**Comment by Moondream15** [comment]
감사합니다!

**Comment by hatemogi** [comment]
@Moondream15 네 문의 감사드립니다. 수작업 번역 실험 프로젝트이고요, 가장 바람직한 것은 역시 깃헙이 직접 공식적으로 한글을 지원해주는 게 좋겠습니다. 

@hsh2001 답변 감사드립니다.
