### ISSUE TITLE
추가 번역 작업을 개인적으로 해보았습니다

### ISSUE THREAD

**Issue by mandoopapa** [hatemogi/github-ko-ext#9]
우선, 좋은 프로그램 제작에 감사드립니다.
이제 갓 프로그래밍 개발 공부를 시작한 학생입니다. 깃허브의 수많은 영어에 멀미하다가 제작 프로그램을 알게되고 알게모르게 많은 도움을 받았습니다. 

Javascript나 html에 대해서는 배운 것이 없는 수준이지만 코드 공부 + 영어 공부 겸 해당 소스를 포크해서 일부분의 번역 작업을 개인적으로 추가해보았습니다. 형식을 제대로 갖추지 못한 부분이 있을거라 개인 연습 차원에서 마무리할까 생각하다가 이렇게 이슈로 남겨드립니다.

추가적으로 더 번역 작업을 진행하고 PR을 드리거나, 혹은 개인적으로 계속해서 진행해서 사용해도 괜찮을지 의견을 부탁드립니다!

**Comment by hatemogi** [comment]
네 @mandoopapa 님, 말씀 감사합니다. PR보내주시면 반영 검토하겠습니다.
